import Head from "next/head";
import React, { ReactNode } from "react";

import Header from "./Header";

type LayoutProps = {
  children: ReactNode;
  siteLogo?: string;
  topInformationBar?: string;
};

export default function Layout({ children, siteLogo, topInformationBar }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Headless WP App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header siteLogo={siteLogo} topInformationBar={topInformationBar}/>
      <main>{children}</main>
    </>
  );
}
