import Head from "next/head";
import React, { ReactNode } from "react";
import Nav from "./Nav";
import Header from "./Header";
import Footer from "./Footer";

type LayoutProps = {
  children: ReactNode;
  siteLogo?: string;
  topInformationBar?: string;
};

// @ts-ignore
export default function Layout({ children, story }) {
  // console.log("layout story", story);

  return (
    <>
      <Head>
        <title>Headless WP App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* @ts-ignore */}
      <Header blok={story?.content} />
      <main className="px-7 xl:px-0">{children}</main>
      <Footer blok={story?.content} />
    </>
  );
}
